# Copyright 2016, 2017 Peter Dimov
# Copyright 2018 Mateusz Loskot <mateusz at loskot dot net>
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)
#
version: 1.0.{build}-{branch}

image: Visual Studio 2017

platform: x64

branches:
  only:
    - master
    - develop
    - ci

shallow_clone: true

environment:
  matrix:
    - TOOLSET: msvc-14.1
      ARCH: x86_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - TOOLSET: msvc-14.1
      ARCH: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - TOOLSET: msvc-14.1
      ARCH: x86_64
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
    - TOOLSET: msvc-14.1
      ARCH: x86
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      APPVEYOR_SAVE_CACHE_ON_ERROR: true

matrix:
  fast_finish: true
  allow_failures:
    - TOOLSET: msvc-14.1
      ARCH: x86_64
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
    - TOOLSET: msvc-14.1
      ARCH: x86
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      APPVEYOR_SAVE_CACHE_ON_ERROR: true

cache:
  - c:\tools\vcpkg\installed\

install:
  - ps: 'Write-Host "Installing CMake module FindBoost.cmake for Boost 1.67+" -ForegroundColor Magenta'
  - appveyor DownloadFile https://raw.githubusercontent.com/Kitware/CMake/master/Modules/FindBoost.cmake -FileName "C:\Program Files (x86)\CMake\share\cmake-3.10\Modules\FindBoost.cmake"
  # FIXME: To be removed https://help.appveyor.com/discussions/problems/13000-cmake_toolchain_filevcpkgcmake-conflicts-with-cmake-native-findboostcmake"
  - ps: 'Write-Host "Installing latest vcpkg.cmake module" -ForegroundColor Magenta'
  - appveyor DownloadFile https://raw.githubusercontent.com/Microsoft/vcpkg/master/scripts/buildsystems/vcpkg.cmake -FileName "c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  - if %ARCH% == x86 ( set "TRIPLET=x86-windows" ) else ( set "TRIPLET=x64-windows" )
  - if %ARCH% == x86 ( set AM=32 ) else ( set AM=64 )
  - vcpkg --triplet %TRIPLET% install libjpeg-turbo libpng tiff
  - if NOT DEFINED GENERATOR set PATH=c:\Tools\vcpkg\installed\%TRIPLET%\bin;%PATH%
  - if NOT DEFINED GENERATOR set VCPKG_I=C:\Tools\vcpkg\installed\%TRIPLET%\include
  - if NOT DEFINED GENERATOR set VCPKG_L=C:\Tools\vcpkg\installed\%TRIPLET%\lib
  - if NOT DEFINED GENERATOR set LIBPNG_NAME=libpng16

before_build:
  - git clone --quiet -b develop --depth 1 https://github.com/boostorg/boost.git c:\projects\boost
  - cd c:\projects\boost
  - git submodule --quiet update --init tools/build
  - git submodule --quiet update --init libs/config
  - git submodule --quiet update --init tools/boostdep
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\gil
  - python tools/boostdep/depinst/depinst.py gil
  - cmd /c bootstrap
  - .\b2 headers
  - if DEFINED GENERATOR .\b2 address-model=%AM% toolset=%TOOLSET% variant=release --with-filesystem --with-test stage

build: off

build_script:
  - cd c:\projects\boost
  - if NOT DEFINED GENERATOR b2 address-model=%AM% toolset=%TOOLSET% variant=release libs/gil/test
  - if NOT DEFINED GENERATOR b2 address-model=%AM% toolset=%TOOLSET% variant=release libs/gil/toolbox/test
  - if NOT DEFINED GENERATOR b2 address-model=%AM% toolset=%TOOLSET% variant=release libs/gil/numeric/test
  - if NOT DEFINED GENERATOR b2 address-model=%AM% toolset=%TOOLSET% variant=release include=%VCPKG_I% library-path=%VCPKG_L% libs/gil/io/test//simple
  - if DEFINED GENERATOR cd libs\gil && md build && cd build
  - if DEFINED GENERATOR cmake -G "%GENERATOR%" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - if DEFINED GENERATOR cmake --build . --config Release

test_script:
  - if DEFINED GENERATOR ctest -V --output-on-failure -C Release

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/e9e4892cdeb7cbff2e5a
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
